### ISSUE TITLE
Progress stops during the download

### ISSUE THREAD

**Issue by Breeze-Zero** [Sage-Bionetworks/synapsePythonClient#1088]
# Bug Report

Progress stops during the download

## Operating system

Ubuntu Linux

## Client version
Newest

## Description of the problem
I used synapse get-download-list in the command line to download data in bulk. In fact, the same thing happens with python scripts. Maybe my network was fluctuating, and it often got stuck halfway after downloading several data. If I was not near the computer, it would remain motionless until I terminated the process, which seriously affected my download experience.
like
Downloading  [###################-]97.26%   2.6GB/4.0GB (3.1MB/s) xxxxxx.synapse_download_138964416

### Expected behavior

If there is a similar timeout detection, the download can be resumed or interrupted by itself?

**Comment by BryanFauble** [comment]
HI @Breeze-Zero ,

Some inital questions:

1. What version of python are you using?
2. What is the Synapse ID that this is failing on?
3. Is this always failing, or inconsistently?

If you run the command line with debug turned on: https://python-docs.synapse.org/tutorials/home/?h=debug#debugging-in-the-client what are you seeing printed out to the console?

I have plans to rewrite the download algorithm; Will be focusing on reliability and speed.

When I was doing some Benchmarking on download speeds I found that modifying the number of threads devoted to the download process adversely affected the stability of the download process. Try lowering the available threads the current algorithm uses. See these resources:
https://python-docs.synapse.org/tutorials/configuration/#transfer

https://python-docs.synapse.org/explanations/benchmarking/#12122023-downloading-files-from-synapse

**Comment by Breeze-Zero** [comment]
@BryanFauble Thank you for your quick response. 
1. I'm currently using python3.9, in fact for quick downloads I'm using multiple machines which also have python 3.8.
2. I downloaded the data set of a challenge, and I need to get permission. One of the data sets has an ID of syn57672057.1
3. It doesn't fail all the time, usually I stop the process and run it again, but it doesn't download just one (actually 200 files), so even if it succeeds, it still happens when downloading other files. I feel more likely to be caused by network fluctuations.

**Comment by BryanFauble** [comment]
>  feel more likely to be caused by network fluctuations.

This is very possible. Or at least related to Synapse rate limits. Limits are shared per account, rather than per machine executing the script. It's possible you could be running these in parallel and causing some downloads to "starve". The current backoff and retry mechanism doesn't work the best - It's one of the items I rewrote I'm 4.2.0 when I redid the upload algorithm. It's something I'll also be addressing for downloads too when I get to it.

Debug logs should uncover a bit more about what's going on here.

A hacky solution for the time being might be to just use a for loop in a Python script and run syn.get() on the file synapse IDs. Some examples I've written around this:
https://python-docs.synapse.org/tutorials/python/download_data_in_bulk/

https://python-docs.synapse.org/reference/oop/models_async/?h=get_async#synapseclient.models.File.get_async

**Comment by BryanFauble** [comment]
@Breeze-Zero v4.4.0 has been officially released - Please install this version and give this a try again when you need to download the content again.

Benchmarked download results: https://python-docs.synapse.org/explanations/benchmarking/#07022024-downloading-files-from-synapse
