### ISSUE TITLE
downloadTableFile behaviour change in 1.7.1 

### ISSUE THREAD

**Issue by telferm57** [Sage-Bionetworks/synapsePythonClient#428]
Hi, I've been using the above method to download mPower files for some time. Just upgraded to synclient 1.7.1 (from 1.6.2 ) and things broke. The method no longer returns a dict , returns string (of the path) instead . Also, if you specify a downloadLocation of "." as per the docs , fails with ' cannot find path "" '. if you leave downloadLocation out, it defaults to the cache, as you'd expect.  both fairly minor , perhaps just doc update required ?

**Comment by kdaily** [comment]
I filed an issue ([SYNPY-503](https://sagebionetworks.jira.com/browse/SYNPY-503)) for the `downloadLocation` and for the return type ([SYNPY-504](https://sagebionetworks.jira.com/browse/SYNPY-504)) in Jira for an engineer to take a look at.

**Comment by zimingd** [comment]
Hi,
We have deprecated `downloadTableFile()` in favor of `downloadTableColumns()` because the former method was very inefficient when downloading multiple files in a `for` loop.  I have updated the documentation for the return value of `downloadTableFile()`, though.

#462 `downloadTableColumns` will have the downloadLocation parameter once the pull request has been reviewed and pulled in. For the time being you may need to manually move the downloaded files of `downloadTableColumns()`.

**Comment by kdaily** [comment]
@telferm57 please re-open if you are still having any issues! Thank you.
