### ISSUE TITLE
download speed, unnecessary REST calls

### ISSUE THREAD

**Issue by wr0112358** [Sage-Bionetworks/synapsePythonClient#686]
# Bug Report
## Operating system
ubuntu 18.04
4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Client version
*Output of:*
```
import synapseclient
synapseclient.__version__
```
'1.9.3'

## Description of the problem
I am trying to download a synapse storage, via synapseutils.syncFromSynapse, but the progress is very slow. The project contains many subfolders(~10k) with 3 files per folder. The download speed is not the problem, rather a REST API request which seems to be made per file in: Synapse::getProvenance.
This function is called in every recursive invocation of synapseutils.syncFromSynapse on all members of allFiles array. Where the allFiles array contains all previously processed files.
One REST-call amounts to t=~100-200ms per call, leading to a duration of (n * t)! for n files.
With ! denoting the factorial.

### Expected behavior
Faster download, do not repeat REST request for all files.

### Actual behavior

*What actually happened? Provide output or error messages from the console, if applicable.*

Is there some fast workaround?

**Comment by kimyen** [comment]
Hi @wr0112358 

Thank you for reporting the problem! I totally agree with your analysis on the unnecessary REST calls. I opened an internal ticket to track this: https://sagebionetworks.jira.com/browse/SYNPY-998

I'm working on improving the Synapse Python client. In the mean time, you may want to check out downloading files from a View as a workaround. Here is my suggestion:
1. create a View with an appropriate scope so that it contains the files you want to download
2. either download using our web client's download list feature
3. or, use Python client `downloadTableColumns`

Please let me know if either of the suggestions above helps.

**Comment by jkiang13** [comment]
@wr0112358 sorry for the slow resolution of this issue.

It is resolved as of the latest Python client version 2.1.1.  During syncFromSynapse getProvenance is called now once only for each file synced no matter how deeply it is nested within the folder hierarchy and the manifest written to each subdirectory only includes the files rooted (recursively) in that subdirectory rather than every file synced so far whether or not the folder was a parent.
