### ISSUE TITLE
support custom Session objects (feature requests)

### ISSUE THREAD

**Issue by zdk123** [Sage-Bionetworks/synapsePythonClient#714]
I have a feature request related to my specific use case. I have a large synapse project where the files themselves are hosted on google drive. The files on synapse are direct link-outs. Unfortunately google drive caps direct download for files over 50MB, instead redirecting the user to download a link with a random confirmation code in the url's query string.

Therefore, the [basic url request](https://github.com/Sage-Bionetworks/synapsePythonClient/blob/master/synapseclient/client.py#L1800-L1803) doesn't quite work for me. I need to stream the file extract the confirmation code, and make a second request, while retaining the cookie from the original request.

I can do all of this in a custom get method (see [my gist](https://gist.github.com/zdk123/8322353ca25fff14a66954e4c4991a0e) for a derivative request.Session class) but I need a way of getting this object into a Synapse client object. See PR #713 for a simple example.

Example usage:
```
import synapseclient
import synapseutils
from gdrivesession import GDriveSession

session = GDriveSession()
syn = synapseclient.Synapse(session=session)
syn.login()
files = synapseutils.syncFromSynapse(syn, "syn20844101")
```

I understand that overwriting get methods for requests might expose the user to security issues or simple user error, but perhaps this is of general interest since there are many urls that are not simply open on the web. At the very least you might want some type/integrity checking on the session object.

Thank you for the consideration.

**Comment by zdk123** [comment]
Fyi, I can currently overwrite the session directly, since the `session` class member is not protected.

```
import synapseclient
import synapseutils
from gdrivesession import GDriveSession

session = GDriveSession()
syn = synapseclient.Synapse()
syn.session = session
```

**Comment by jkiang13** [comment]
Sorry for the late response.

Setting the requests_session in the Synapse object constructor will be supported in the upcoming 2.1.0 release of the Synapse Python client, e.g.

`syn = synapseclient.Synapse(requests_session=session)`

The session must be a requests Session object (but it sounds like your GDriveSession is a subclass so that should work). This will have the same effect as setting it directly on the object as you are doing now and that will continue to work, although setting to private members (i.e. underscore prefixed) is not recommended and may break in a future version.

A release candidate including this is available now from [test.pypi.org](https://test.pypi.org/project/synapseclient/) and will a final release will be available soon.

**Comment by zdk123** [comment]
Excellent, thank you!

> although setting to private members (i.e. underscore prefixed) is not recommended and may break in a future version.

thanks for the warning!
